name: Build package

on: [push]

jobs:
  build:

    name: Test build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install dependencies
      run: sudo apt-get install -y git-buildpackage debhelper dkms lsb-release
    - name: Environment survey
      run:
        lsb_release -a && uname -a
    - name: Build
      run: dpkg-buildpackage -us -uc
    - name: Test install
      run: sudo dpkg -i ../facetimehd-dkms_*.deb ; cat /var/lib/dkms/facetimehd/*/build/make.log || true
    - name: Check install
      run: modinfo facetimehd
