name: Build package

on: [push]

jobs:
  build:

    name: Test build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install dependencies
      run: sudo apt-get install -y --no-install-recommends build-essential devscripts equivs
    - name: Install deb dependencies
      run: mk-build-deps && sudo apt install -y --no-install-recommends ./facetimehd-dkms-build-deps*deb && git clean -xfd
    - name: Build
      run: dpkg-buildpackage -us -uc
    - name: Test install
      run: sudo apt install ../facetimehd-dkms_*.deb ; cat /var/lib/dkms/facetimehd/*/build/*/make.log || true
    - name: Check install
      run: modinfo facetimehd
